// Scenario definitions converted from Postman collection

import type { Scenario } from './types';

export const scenarios: Scenario[] = [
  // ===========================================
  // 3DS Challenge Flow
  // ===========================================
  {
    id: '3ds-challenge-flow',
    name: '3DS Challenge Flow',
    description: 'Full 3DS challenge flow demonstrating Strong Customer Authentication (SCA). The cardholder is redirected to complete authentication with their bank.',
    tags: ['3DS', 'CARD', 'AUTH', 'CHALLENGE'],
    steps: [
      {
        id: 'get-session-token',
        name: 'Get Session Token',
        description: 'Initialize a session with Nuvei. This is the first step in any payment flow.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'init-payment-3ds',
        name: 'Initialize Payment (3DS)',
        description: 'Check if the card supports 3DS and get the 3DS version.',
        endpoint: '/ppp/api/initPayment.do',
        method: 'POST',
        checksumFields: [],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          sessionToken: '{{ctx.sessionToken}}',
          clientRequestId: '{{meta.clientRequestId}}',
          currency: 'USD',
          amount: '500',
          userTokenId: 'demo-user',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'CL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodNotificationUrl: 'https://example.com/3ds-method-notification',
                platformType: '01',
              },
            },
          },
        },
        contextReads: ['sessionToken'],
        contextWrites: {
          'transactionId': 'initPaymentTransactionId',
          'paymentOption.card.threeD.version': 'threeDVersion',
        },
      },
      {
        id: 'payment-challenge',
        name: 'Payment (Challenge)',
        description: 'Submit the payment request. This card triggers a 3DS challenge.',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '150',
          relatedTransactionId: '{{ctx.initPaymentTransactionId}}',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'CL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodCompletionInd: 'U',
                version: '{{ctx.threeDVersion}}',
                notificationURL: 'https://docs.nuvei.com/3Dsimulator/notificationUrl.php',
                merchantURL: 'https://example.com',
                platformType: '02',
                v2AdditionalParams: {
                  challengePreference: '01',
                  challengeWindowSize: '05',
                },
                browserDetails: {
                  acceptHeader: 'text/html,application/xhtml+xml',
                  ip: '192.168.1.11',
                  javaEnabled: 'TRUE',
                  javaScriptEnabled: 'TRUE',
                  language: 'EN',
                  colorDepth: '48',
                  screenHeight: '400',
                  screenWidth: '600',
                  timeZone: '0',
                  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47)',
                },
              },
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'initPaymentTransactionId', 'threeDVersion'],
        contextWrites: {
          'transactionId': 'paymentTransactionId',
          'paymentOption.card.threeD.acsUrl': 'acsUrl',
          'paymentOption.card.threeD.cReq': 'cReq',
        },
        is3DSChallenge: true,
      },
      {
        id: 'payment-liability-shift',
        name: 'Payment (Liability Shift)',
        description: 'Complete the payment after 3DS challenge. The liability shifts to the issuer.',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          relatedTransactionId: '{{ctx.paymentTransactionId}}',
          currency: 'EUR',
          amount: '150',
          transactionType: 'Auth',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'CL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'paymentTransactionId'],
        contextWrites: {
          'transactionId': 'relatedTransactionId',
          'authCode': 'authCode',
        },
      },
    ],
  },

  // ===========================================
  // 3DS Frictionless Flow
  // ===========================================
  {
    id: '3ds-frictionless-flow',
    name: '3DS Frictionless Flow',
    description: 'Payment with 3DS but no challenge required. The bank authenticates silently based on risk assessment.',
    tags: ['3DS', 'CARD', 'AUTH', 'FRICTIONLESS'],
    steps: [
      {
        id: 'get-session-token',
        name: 'Get Session Token',
        description: 'Initialize a session with Nuvei.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'init-payment-3ds',
        name: 'Initialize Payment (3DS)',
        description: 'Check if the card supports 3DS using a frictionless test card.',
        endpoint: '/ppp/api/initPayment.do',
        method: 'POST',
        checksumFields: [],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          sessionToken: '{{ctx.sessionToken}}',
          clientRequestId: '{{meta.clientRequestId}}',
          currency: 'USD',
          amount: '500',
          userTokenId: 'demo-user',
          paymentOption: {
            card: {
              cardNumber: '4000027891380961',
              cardHolderName: 'FL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodNotificationUrl: 'https://example.com/3ds-method-notification',
                platformType: '01',
              },
            },
          },
        },
        contextReads: ['sessionToken'],
        contextWrites: {
          'transactionId': 'initPaymentTransactionId',
          'paymentOption.card.threeD.version': 'threeDVersion',
        },
      },
      {
        id: 'payment-frictionless',
        name: 'Payment (Frictionless)',
        description: 'Submit payment. This card will be approved without a challenge.',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '150',
          relatedTransactionId: '{{ctx.initPaymentTransactionId}}',
          paymentOption: {
            card: {
              cardNumber: '4000027891380961',
              cardHolderName: 'FL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodCompletionInd: 'U',
                version: '{{ctx.threeDVersion}}',
                notificationURL: 'https://example.com/notification',
                merchantURL: 'https://example.com',
                platformType: '02',
                v2AdditionalParams: {
                  challengePreference: '01',
                  challengeWindowSize: '05',
                },
                browserDetails: {
                  acceptHeader: 'text/html,application/xhtml+xml',
                  ip: '192.168.1.11',
                  javaEnabled: 'TRUE',
                  javaScriptEnabled: 'TRUE',
                  language: 'EN',
                  colorDepth: '48',
                  screenHeight: '400',
                  screenWidth: '600',
                  timeZone: '0',
                  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47)',
                },
              },
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'initPaymentTransactionId', 'threeDVersion'],
        contextWrites: {
          'transactionId': 'paymentTransactionId',
          'authCode': 'authCode',
        },
      },
    ],
  },

  // ===========================================
  // Simple Auth + Settle Flow
  // ===========================================
  {
    id: 'simple-auth-settle',
    name: 'Simple Auth + Settle',
    description: 'Basic authorization followed by settlement (capture). No 3DS required.',
    tags: ['CARD', 'AUTH', 'SETTLE', 'SIMPLE'],
    steps: [
      {
        id: 'get-session-token',
        name: 'Get Session Token',
        description: 'Initialize a session with Nuvei.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'payment-auth',
        name: 'Authorization',
        description: 'Authorize a payment (reserve funds on the card).',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '10',
          transactionType: 'Auth',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'John Smith',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken'],
        contextWrites: {
          'transactionId': 'paymentTransactionId',
          'authCode': 'paymentAuthCode',
        },
      },
      {
        id: 'settle-transaction',
        name: 'Settle Transaction',
        description: 'Capture the authorized payment (transfer funds).',
        endpoint: '/ppp/api/settleTransaction.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'clientUniqueId', 'amount', 'currency', 'relatedTransactionId', 'authCode', 'descriptorMerchantName', 'descriptorMerchantPhone', 'comment', 'urlDetails.notificationUrl', 'timeStamp'],
        requestTemplate: {
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          clientUniqueId: '{{meta.clientRequestId}}',
          amount: '10',
          currency: 'EUR',
          relatedTransactionId: '{{ctx.paymentTransactionId}}',
          authCode: '{{ctx.paymentAuthCode}}',
          urlDetails: {
            notificationUrl: '',
          },
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: ['paymentTransactionId', 'paymentAuthCode'],
        contextWrites: {
          'transactionId': 'settleTransactionId',
          'authCode': 'settleAuthCode',
        },
      },
      {
        id: 'get-payment-status',
        name: 'Get Payment Status',
        description: 'Verify the transaction status.',
        endpoint: '/ppp/api/getPaymentStatus.do',
        method: 'POST',
        checksumFields: [],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
        },
        contextReads: ['sessionToken'],
        contextWrites: {},
      },
    ],
  },

  // ===========================================
  // External MPI Flow
  // ===========================================
  {
    id: 'external-mpi',
    name: 'External MPI',
    description: 'Payment using 3DS data from an external MPI provider. Pass eci, cavv, and dsTransID from your own 3DS service.',
    tags: ['3DS', 'CARD', 'MPI', 'EXTERNAL'],
    steps: [
      {
        id: 'get-session-token',
        name: 'Get Session Token',
        description: 'Initialize a session with Nuvei.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'payment-external-mpi',
        name: 'Payment with External MPI',
        description: 'Submit payment with 3DS values from external MPI provider.',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '10',
          transactionType: 'Auth',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'CL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                externalMpi: {
                  eci: '2',
                  cavv: 'ejJRWG9SWWRpU2I1M21DelozSXU=',
                  dsTransID: '9e6c6e9b-b390-4b11-ada9-0a8f595e8600',
                },
              },
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken'],
        contextWrites: {
          'transactionId': 'relatedTransactionId',
          'authCode': 'authCode',
        },
      },
    ],
  },

  // ===========================================
  // MPI Only (3DS as a Service)
  // ===========================================
  {
    id: 'mpi-only',
    name: 'MPI Only (3DS as a Service)',
    description: 'Use Nuvei only for 3DS authentication, then process payment elsewhere. Get eci, cavv, dsTransID.',
    tags: ['3DS', 'MPI', 'AUTH'],
    steps: [
      {
        id: 'get-session-token',
        name: 'Get Session Token',
        description: 'Initialize a session with Nuvei.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'init-payment-3ds',
        name: 'Initialize Payment',
        description: 'Initialize the 3DS process.',
        endpoint: '/ppp/api/initPayment.do',
        method: 'POST',
        checksumFields: [],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          sessionToken: '{{ctx.sessionToken}}',
          clientRequestId: '{{meta.clientRequestId}}',
          currency: 'USD',
          amount: '150',
          userTokenId: 'demo-user',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'FL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodNotificationUrl: 'https://example.com/3ds-method-notification',
                platformType: '01',
              },
            },
          },
        },
        contextReads: ['sessionToken'],
        contextWrites: {
          'transactionId': 'initPaymentTransactionId',
          'paymentOption.card.threeD.version': 'threeDVersion',
        },
      },
      {
        id: 'authorize3d',
        name: 'Authorize 3D',
        description: 'Perform 3DS authentication. May trigger a challenge.',
        endpoint: '/ppp/api/authorize3d.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '150',
          relatedTransactionId: '{{ctx.initPaymentTransactionId}}',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'CL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodCompletionInd: 'U',
                version: '{{ctx.threeDVersion}}',
                notificationURL: 'https://docs.nuvei.com/3Dsimulator/notificationUrl.php',
                merchantURL: 'https://example.com',
                platformType: '02',
                v2AdditionalParams: {
                  challengePreference: '01',
                  challengeWindowSize: '05',
                },
                browserDetails: {
                  acceptHeader: 'text/html,application/xhtml+xml',
                  ip: '192.168.1.11',
                  javaEnabled: 'TRUE',
                  javaScriptEnabled: 'TRUE',
                  language: 'EN',
                  colorDepth: '48',
                  screenHeight: '400',
                  screenWidth: '600',
                  timeZone: '0',
                  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47)',
                },
              },
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'initPaymentTransactionId', 'threeDVersion'],
        contextWrites: {
          'transactionId': 'paymentTransactionId',
          'paymentOption.card.threeD.acsUrl': 'acsUrl',
          'paymentOption.card.threeD.cReq': 'cReq',
        },
        is3DSChallenge: true,
      },
      {
        id: 'verify3d',
        name: 'Verify 3D',
        description: 'Complete 3DS verification after challenge. Returns eci, cavv, dsTransID.',
        endpoint: '/ppp/api/verify3d.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '150',
          relatedTransactionId: '{{ctx.paymentTransactionId}}',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'CL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'paymentTransactionId'],
        contextWrites: {
          'paymentOption.card.threeD.dsTransID': 'dsTransID',
          'paymentOption.card.threeD.cavv': 'cavv',
          'paymentOption.card.threeD.eci': 'eci',
        },
      },
    ],
  },

  // ===========================================
  // Recurring with 3DS
  // ===========================================
  {
    id: 'recurring-3ds',
    name: 'Recurring with 3DS',
    description: 'Set up recurring payments with initial 3DS authentication. Subsequent payments use stored credentials.',
    tags: ['RECURRING', 'CARD', '3DS', 'MIT'],
    steps: [
      {
        id: 'get-session-token',
        name: 'Get Session Token',
        description: 'Initialize a session for the initial recurring payment.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'init-payment-3ds',
        name: 'Initialize Payment',
        description: 'Initialize 3DS for the first recurring payment.',
        endpoint: '/ppp/api/initPayment.do',
        method: 'POST',
        checksumFields: [],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          sessionToken: '{{ctx.sessionToken}}',
          clientRequestId: '{{meta.clientRequestId}}',
          currency: 'USD',
          amount: '500',
          userTokenId: 'recurringUser',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'FL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodNotificationUrl: 'https://example.com/3ds-method-notification',
                platformType: '01',
              },
            },
          },
        },
        contextReads: ['sessionToken'],
        contextWrites: {
          'transactionId': 'initPaymentTransactionId',
          'paymentOption.card.threeD.version': 'threeDVersion',
        },
      },
      {
        id: 'initial-payment',
        name: 'Initial MIT Payment',
        description: 'First payment in recurring cycle with 3DS.',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          currency: 'EUR',
          amount: '150',
          relatedTransactionId: '{{ctx.initPaymentTransactionId}}',
          userTokenId: 'recurringUser',
          isRebilling: '0',
          rebillingType: 'RECURRING',
          paymentOption: {
            card: {
              cardNumber: '4000020951595032',
              cardHolderName: 'FL-BRW1',
              expirationMonth: '12',
              expirationYear: '25',
              CVV: '217',
              threeD: {
                methodCompletionInd: 'U',
                version: '{{ctx.threeDVersion}}',
                notificationURL: 'https://example.com/notification',
                merchantURL: 'https://example.com',
                platformType: '02',
                v2AdditionalParams: {
                  rebillExpiry: '20261231',
                  rebillFrequency: '30',
                },
                browserDetails: {
                  acceptHeader: 'text/html,application/xhtml+xml',
                  ip: '192.168.1.11',
                  javaEnabled: 'TRUE',
                  javaScriptEnabled: 'TRUE',
                  language: 'EN',
                  colorDepth: '48',
                  screenHeight: '400',
                  screenWidth: '600',
                  timeZone: '0',
                  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47)',
                },
              },
            },
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'initPaymentTransactionId', 'threeDVersion'],
        contextWrites: {
          'transactionId': 'paymentTransactionId',
          'paymentOption.userPaymentOptionId': 'userPaymentOptionId',
        },
      },
      {
        id: 'get-session-token-subsequent',
        name: 'Get Session Token (Subsequent)',
        description: 'New session for the subsequent recurring payment.',
        endpoint: '/ppp/api/getSessionToken.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'timeStamp'],
        requestTemplate: {
          merchantSiteId: '{{env.merchantSiteId}}',
          merchantId: '{{env.merchantId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
        },
        contextReads: [],
        contextWrites: {
          'sessionToken': 'sessionToken',
        },
      },
      {
        id: 'subsequent-payment',
        name: 'Subsequent MIT Payment',
        description: 'Recurring payment using stored credentials (no 3DS required).',
        endpoint: '/ppp/api/payment.do',
        method: 'POST',
        checksumFields: ['merchantId', 'merchantSiteId', 'clientRequestId', 'amount', 'currency', 'timeStamp'],
        requestTemplate: {
          sessionToken: '{{ctx.sessionToken}}',
          merchantId: '{{env.merchantId}}',
          merchantSiteId: '{{env.merchantSiteId}}',
          clientRequestId: '{{meta.clientRequestId}}',
          timeStamp: '{{meta.timestamp}}',
          checksum: '',
          relatedTransactionId: '{{ctx.paymentTransactionId}}',
          isRebilling: '1',
          userTokenId: 'recurringUser',
          currency: 'EUR',
          amount: '10',
          paymentOption: {
            userPaymentOptionId: '{{ctx.userPaymentOptionId}}',
          },
          billingAddress: {
            firstName: 'John',
            lastName: 'Smith',
            address: '340689 main St.',
            city: 'London',
            country: 'GB',
            email: 'john.smith@example.com',
          },
          deviceDetails: {
            ipAddress: '93.146.254.172',
          },
        },
        contextReads: ['sessionToken', 'paymentTransactionId', 'userPaymentOptionId'],
        contextWrites: {
          'transactionId': 'relatedTransactionId',
          'authCode': 'authCode',
        },
      },
    ],
  },
];
